### ISSUE TITLE
install_gnparser() is broken

### ISSUE THREAD

**Issue by joelnitta** [ropensci/rgnparser#17]
```
rgnparser::install_gnparser(force = TRUE)
The latest gnparser version is v1.6.9
Error in utils::download.file(grep(os, urls, value = TRUE), file, mode = "wb") : 
  'url' must be a length-one character vector
```

Same error shows up in [github workflow "R-check"](https://github.com/ropensci/rgnparser/actions/runs/3887163465/jobs/6633103097)

**Comment by joelnitta** [comment]
This seems to be caused by a change in the way gnparser is released. In [v1.3.1](https://github.com/gnames/gnparser/releases/tag/v1.3.1) and prior, there were three binaries, one for each OS. So `install_gnparser()` [simply detected the OS](https://github.com/ropensci/rgnparser/blob/b99132138b86f471ff6574e19d23afe6e6508f37/R/install_gnparser.R#L114-L115) from `.Platform` (Windows) or `Sys.info()` (Mac, Linux), then selected the appropriate binary.

But [starting in v1.3.2](https://github.com/gnames/gnparser/releases/tag/v1.3.2) there are multiple binaries for each OS. Now there are three for Mac and two each for Windows and Linux. For example [v1.6.9](https://github.com/gnames/gnparser/releases/tag/v1.6.9) (as of writing, most current) has:

- gnparser-v1.6.9-linux.tar.gz
- gnparser-v1.6.9-mac-arm64.tar.g
- gnparser-v1.6.9-mac.tar.gz
- gnparser-v1.6.9-win-64.zip
- macos-latest-clib.zip
- ubuntu-latest-clib.zip
- windows-latest-clib.zip

The [`grep()` pattern used by `install_gnparser()`](https://github.com/ropensci/rgnparser/blob/b99132138b86f471ff6574e19d23afe6e6508f37/R/install_gnparser.R#L66) then hits multiple URLs instead of only 1 and we get the error in the OP.

So we need to narrow down the binary to be installed only one, but the question is how to determine this from information about the user's OS available in `.Platform` or `Sys.info()`.

**Comment by joelnitta** [comment]
I'm not sure what the `-clib.zip` formats are, but my guess is they are for [using gnparser as a shared C library](https://github.com/gnames/gnparser#use-as-a-shared-c-library) (perhaps @dimus can confirm).

This is probably not the typical use-case for {rgnparser}, so I think we can ignore those (or just mention them in the documentation and indicate that they should be manually installed if desired).

That leaves differentiating between arm64 or not for Mac.

**Comment by AlbanSagouis** [comment]
For differentiating between arm64 and Intel chips, here is a test found in ropensci/wdman/R/utils.R
```
# Figure out if installing on an Intel or M1 mac
mac_machine <- function() {
  ifelse(Sys.info()[["machine"]] == "arm64", "mac(64_|os-)", "mac(64|os)$")
}
```

`rgnparser::install_gnparser()` depends on `rgnparser:::bin_paths()` that will need updating too as I believe libraries are located in a different folder in Macs with Intel and Apple chips

**Comment by dimus** [comment]
@jeroen thats right `-clib.zip` files are for incoporating gnparser as a C library (for example https://github.com/amazingplants/node-gnparser)

**Comment by joelnitta** [comment]
@dimus perhaps you mean @joelnitta not @jeroen, but thanks!
